version: "2"

services:
  panel:
    image: hydro-monitor/admin-panel:v0.0.0
    ports:
      - 3000:3000
    container_name: "hydromon-admin-panel"
    depends_on:
      - panel-api-proxy

  panel-api-proxy: # HA Proxy service
    image: haproxy:2.0.16 # Official HAProxy image
    ports:
      - 3001:3001
    container_name: "hydromon-panel-haproxy"
    volumes: # HAProxy configuration volume mount
      - ".:/usr/local/etc/haproxy/haproxy.cfg:ro"
