version: "2"

services:
  panel:
    image: hydro-monitor/admin-panel:v0.0.0
    ports:
      - 80:3000
    container_name: "hydromon-admin-panel"
    networks:
      - hydromon-net
    env_file:
      - .env.development
    depends_on:
      - panel-api-proxy

  panel-api-proxy: # HA Proxy service
    image: haproxy:2.0.16 # Official HAProxy image
    container_name: "hydromon-panel-haproxy"
    networks:
      - hydromon-net
    volumes: # HAProxy configuration volume mount
      - ".:/usr/local/etc/haproxy/haproxy.cfg:ro"

networks:
  hydromon-net:
    external: true
